#!/bin/bash

set -e


if [ "$1" = "remove" ] ; then

	PKG="lliurex-live-fixes"

	ORIGINAL_MICROCODE_FILE="/usr/share/initramfs-tools/hooks/intel_microcode"
	DIVERTED_MICROCODE="/usr/share/lliurex-live-fixes/diversions/intel_microcode"
	
	if [ -e "$DIVERTED_MICROCODE" ]; then
		if [ -e $ORIGINAL_MICROCODE_FILE ]; then
			rm $ORIGINAL_MICROCODE_FILE || true
		fi
                dpkg-divert --remove --package ${PKG} --rename --divert "$DIVERTED_MICROCODE" "$ORIGINAL_MICROCODE_FILE"
		

        fi

	ORIGINAL_MICROCODE_FILE="/usr/share/initramfs-tools/hooks/amd64_microcode"
	DIVERTED_MICROCODE="/usr/share/lliurex-live-fixes/diversions/amd64_microcode"
	
	if [ -e "$DIVERTED_MICROCODE" ]; then

		if [ -e $ORIGINAL_MICROCODE_FILE ]; then
                        rm $ORIGINAL_MICROCODE_FILE || true
                fi

                dpkg-divert --remove --package ${PKG} --rename --divert "$DIVERTED_MICROCODE" "$ORIGINAL_MICROCODE_FILE"
		

        fi


        ORIGINAL_MYSQL_FILE="/usr/sbin/mysqld"
        DIVERTED_MYSQL="/usr/share/lliurex-live-fixes/diversions/mysqld"


        if [ ! -e "DIVERTED_MYSQL" ]; then

		if [ -L "/usr/sbin/mysqld" ]; then
			rm -rf /usr/sbin/mysqld
		fi

		dpkg-divert --remove --package ${PKG} --rename --divert "$DIVERTED_MYSQL" "$ORIGINAL_MYSQL_FILE"
        fi



	N4D_ONESHOT_DIR="/etc/n4d/one-shot/"
	PACKAGE_ONESHOTS_DIR="/usr/share/lliurex-live-fixes/n4d-oneshots"

	if [ ! -d $N4D_ONESHOT_DIR ]; then
	
		mkdir -p $N4D_ONESHOT_DIR || true

	fi

	cp "$PACKAGE_ONESHOTS_DIR/*" $N4D_ONESHOT_DIR || true


fi
#DEBHELPER#

exit 0
