#!/bin/sh

PREREQ=""
DESCRIPTION="Setting ca_ES.utf8@valencia if necessary..."

prereqs()
{
	echo $PREREQ
}


CA_LANG="@valencia"
LOCALE_FILE="/root/etc/default/locale"
LOCALE_GEN_FILE="/root/etc/locale.gen"

RC=0
grep $CA_LANG /proc/cmdline 1>/dev/null 2>/dev/null || RC=1

if [ $RC = 0 ]; then

	echo "[LliureX] Creating new etc/default/locale ..."

	cat > $LOCALE_FILE << EOF
LANG=ca_ES.utf8@valencia
LC_ALL=ca_ES.UTF-8
EOF

fi

