#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring openssh-server..."

prereqs()
{
    echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"
# Only in casper mode
rc=0
cat /proc/cmdline | grep -q "casper" ||rc=1
if [ ${rc} -eq 0 ]; then
	casper-reconfigure /root openssh-server
else
	echo " Disabled (not in casper)"
fi
log_end_msg
